version: "3.9"
services:
  web:
    build: .
    command: /code/start.sh
    ports:
      - "8080:80"
      - "8081:81"
    volumes:
      - .:/code
  vue:
    build: .
    command: /code/startvue.sh
    ports:
      - "8080:80"
    volumes:
      - .:/code
  install:
    build: .
    command: /code/install.sh
    volumes:
      - .:/code