name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        lfs: true
    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - name: Checkout LFS objects
      run: git lfs pull
    - name: Install dependencies (nuget)
      run: dotnet restore
      working-directory: ./Server
    - name: Build Server
      run: dotnet publish -c Release
      working-directory: ./Server
    - name: Archive built server application
      uses: actions/upload-artifact@v2
      with:
        name: server
        path: Server/bin/Release/net5.0/publish
    - name: Install dependencies (npm)
      run: npm ci
      working-directory: ./ClientApp
    - name: Build Client
      run: npm run build
      working-directory: ./ClientApp
    - name: Archive built client application
      uses: actions/upload-artifact@v2
      with:
        name: client
        path: ClientApp/dist

  #deploy:
  #  needs: build
  #  runs-on: ubuntu-latest
  #  steps:
  #  - name: Trigger webhook
  #    run: curl -s http://bootgen.com:9000/hooks/update?token=${{ secrets.WEBHOOK_TOKEN }}
