name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        lfs: true
    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - name: Checkout LFS objects
      run: git lfs pull
    - name: Install dependencies (nuget)
      run: dotnet restore
      working-directory: ./Server
    - name: Build Server
      run: dotnet publish -c Release
      working-directory: ./Server
    - name: Archive built server application
      uses: actions/upload-artifact@v2
      with:
        name: server
        path: Server/bin/Release/net6.0/publish
    - name: Install dependencies (npm, desktop)
      run: npm ci
      working-directory: ./ClientApp
    - name: Build Client (desktop)
      run: npm run build
      working-directory: ./ClientApp
    - name: Archive built client application (desktop)
      uses: actions/upload-artifact@v2
      with:
        name: client
        path: ClientApp/dist
    - name: Install dependencies (npm, mobile)
      run: npm ci
      working-directory: ./MobileApp
    - name: Build Client (mobile)
      run: npm run build
      working-directory: ./MobileApp
    - name: Archive built client application (mobile)
      uses: actions/upload-artifact@v2
      with:
        name: mobile
        path: MobileApp/dist


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Trigger webhook
      run: curl -s http://vuestart.com:9000/hooks/update-vuestart?token=${{ secrets.WEBHOOK_TOKEN }}
